server:
  port: 8080

spring:
  application:
    name: studentcrm

  datasource:
    url: jdbc:mysql://localhost:3306/course
    username: root
    password: your_password
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
    hibernate:
      ddl-auto: update


  jwt:
    token:
      validity: 18000
    signing:
      key: 357638792F423F4428472B4B6250655368566D597133743677397A2443264629
    authorities:
      key: roles
      prefix: Bearer
    header:
      string: Authorization

#  springdoc:
#    swagger-ui:
#      path: /swagger-ui.html
#      url: /v3/api-docs
#    api-docs:
#      path: /v3/api-docs