server:
  port: 8080

spring:
  application:
    name: studentcrm

  datasource:
    url: jdbc:postgresql://localhost:54032/course
    username: sanan
    password: Test@123
    driver-class-name: org.postgresql.Driver

  jpa:
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
